-- SQL commands to set up the gaming club database tables in the Supabase SQL Editor.
-- WARNING: This will drop existing 'rooms' and 'spendings' tables to recreate them with the correct columns.

-- Drop existing tables to ensure correct column schema
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS spendings CASCADE;

-- 1. Create the 'rooms' table
CREATE TABLE rooms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    equipment TEXT,
    "pricePerHour" NUMERIC,
    status TEXT DEFAULT 'available',
    game TEXT,
    player TEXT,
    since TEXT,
    revenue NUMERIC DEFAULT 0,
    "startTime" BIGINT,
    "endTime" BIGINT,
    "sessionMode" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for rooms
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;

-- Create public access policies for rooms (allow all operations for development)
CREATE POLICY "Allow public select for rooms" ON rooms FOR SELECT USING (true);
CREATE POLICY "Allow public insert for rooms" ON rooms FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update for rooms" ON rooms FOR UPDATE USING (true);
CREATE POLICY "Allow public delete for rooms" ON rooms FOR DELETE USING (true);

-- Seed initial rooms data (optional)
INSERT INTO rooms (number, type, equipment, "pricePerHour", status, revenue)
VALUES 
('A-01', 'VIP Suite', 'PS5', 30000, 'available', 0),
('A-02', 'Standard', 'PS3', 15000, 'available', 0),
('A-03', 'VIP Suite', 'PS5', 30000, 'available', 0),
('B-01', 'Standard', 'PS3', 15000, 'available', 0),
('B-02', 'Premium', 'PS4', 20000, 'available', 0),
('B-03', 'Standard', 'PS3', 15000, 'available', 0),
('C-01', 'Premium', 'PS4', 20000, 'available', 0),
('C-02', 'Standard', 'PS3', 15000, 'available', 0),
('C-03', 'VIP Suite', 'PS5', 30000, 'available', 0),
('D-01', 'Standard', 'PS3', 15000, 'available', 0),
('D-02', 'Premium', 'PS4', 20000, 'available', 0),
('D-03', 'Standard', 'PS3', 15000, 'available', 0)
ON CONFLICT (number) DO NOTHING;


-- 2. Create the 'spendings' table
CREATE TABLE spendings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    date TEXT NOT NULL,
    icon TEXT,
    color TEXT,
    type TEXT DEFAULT 'expense',
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for spendings
ALTER TABLE spendings ENABLE ROW LEVEL SECURITY;

-- Create public access policies for spendings
CREATE POLICY "Allow public select for spendings" ON spendings FOR SELECT USING (true);
CREATE POLICY "Allow public insert for spendings" ON spendings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update for spendings" ON spendings FOR UPDATE USING (true);
CREATE POLICY "Allow public delete for spendings" ON spendings FOR DELETE USING (true);

-- Seed initial spendings data (optional)
INSERT INTO spendings (name, category, amount, date, icon, color, type)
VALUES 
('Kompyuter qismlarini yangilash', 'Jihozlar', 45000000, '2025-05-01', '🖥️', 'rgba(124,58,237,0.2)', 'expense'),
('Elektr energiyasi to''lovi', 'Kommunal', 8200000, '2025-05-05', '⚡', 'rgba(245,158,11,0.2)', 'expense'),
('Kofe va yeguliklar zaxirasi', 'Bar', 3500000, '2025-05-06', '☕', 'rgba(6,182,212,0.2)', 'expense'),
('O''yin o''rindiqlari x4', 'Mebel', 12000000, '2025-05-08', '🪑', 'rgba(16,185,129,0.2)', 'expense'),
('Internet obunasi', 'Kommunal', 2000000, '2025-05-10', '🌐', 'rgba(6,182,212,0.2)', 'expense'),
('O''yin litsenziyalari (Steam)', 'Dasturiy ta''minot', 6800000, '2025-05-11', '🎮', 'rgba(139,92,246,0.2)', 'expense'),
('Xodimlar oyligi', 'Xodimlar (Kassa)', 110500000, '2025-05-01', '👥', 'rgba(239,68,68,0.2)', 'expense'),
('Tozalash vositalari', 'Texnik xizmat', 1300000, '2025-05-12', '🧹', 'rgba(16,185,129,0.2)', 'expense');
